global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['webhook:9093']

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'ws1'
    static_configs:
      - targets: ['web-service-1:8081']

  - job_name: 'ws2'
    static_configs:
      - targets: ['web-service-2:8082']

  - job_name: 'ws3'
    static_configs:
      - targets: ['web-service-2:8083']
