global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'wazuh-webhook'

receivers:
  - name: 'wazuh-webhook'
    webhook_configs:
      - url: 'http://alert-webhook:9093/webhook'
        http_config:
          authorization:
            type: Bearer
            credentials_file: /tmp/wazuh_token
        max_alerts: 0

templates:
  - '/etc/alertmanager/config/*.tmpl'
