global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'instance']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'wazuh-webhook'

receivers:
  - name: 'wazuh-webhook'
    webhook_configs:
      - url: 'http://prometheus-webhook:5001/alert'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
